version: '3.9'

services:

  python:
    build: ./images/python/.
    container_name: python
    volumes:
      - ./volumes/src/python:/app
    ports:
      - 5000:5000
    depends_on:
      - redis
    command: python3 app.py

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./volumes/db/redis:/data
  
  node:
    image: node:8-slim
    container_name: node
    volumes:
      - ./volumes/src/node:/app
    depends_on:
      - mongo
    command: node /app/app.js

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./volumes/db/mongo:/data/db
  
  php:
    build: ./images/php/.
    container_name: php
    ports:
      - 80:80
    volumes:
      - ./volumes/src/php:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./volumes/db/mysql:/var/lib/mysql
    environment:   
      MYSQL_ROOT_PASSWORD: xpto
      MYSQL_DATABASE: xpto

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - db