version: '3.9'

services:

  python:
    image: python:3.9
    tty: true
    container_name: python
    volumes:
      - ./volumes/src/python:/usr/src/app  
  
  node:
    image: node:8-slim
    tty: true
    container_name: node
    volumes:
      - ./volumes/src/node:/home/node/app
  
  php:
    build: ./images/php/.
    container_name: php
    ports:
      - 80:80
    volumes:
      - ./volumes/src/php:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 9906:3306
    volumes:
      - ./volumes/db/mysql:/var/lib/mysql
    environment:   
      MYSQL_ROOT_PASSWORD: xpto
      MYSQL_DATABASE: xpto #Cria uma base de dados chamada xpto quando a máquina é iniciada
      MYSQL_USER: xpto #Cria um utilizador para a base de dados acima
      MYSQL_PASSWORD: xpto #Cria uma password para o utilizador acima

  
  mongodb:
    image: mongo:5.0
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./volumes/db/mongo:/data/db
  
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./volumes/db/redis:/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080